import {selectLegendTargets} from '../lib/legend-targets.mjs';

const legend = document.querySelector<HTMLElement>('#quick-legend');
const letter = document.querySelector<HTMLElement>('.letter-content');

if (legend && letter) {
  const panel = legend;
  const content = letter;
  const scroller = panel.querySelector<HTMLElement>('.quick-legend-body')!;
  const overlay = panel.querySelector<SVGSVGElement>('.legend-connections')!;
  const rows = [...panel.querySelectorAll<HTMLElement>('[data-legend-tag]')];
  const svgNS = 'http://www.w3.org/2000/svg';
  const textMeasure = document.createElement('canvas').getContext('2d')!;
  const selectors: Record<string, string> = {
    b: 'strong', it: 'em', aq: '.aq', ink: '.ink', pe: '.pe',
    hand: '.hand, .hand-label [data-hand-ref], .sidenote-details [data-hand-ref], .hand-key [data-hand-ref]',
    ul: '.ul, .dul, .tul', highlight: '.highlight',
    del: 'del:not(del del, .subst del, .undo del)', er: '.er',
    insertion: '.insertion:not(.subst .insertion)', subst: '.subst', undo: '.undo',
    note: '.note', tl: '.tl', nr: '.nr', vspace: '.lb-vspace',
    page: '.page-anchor[data-break="inline"], .page-number a',
    sidenote: '.sidenote-position',
  };
  type Circle = {x: number; y: number; radius: number};
  let scheduled = false;

  function visibleCircle(rect: DOMRect, target: HTMLElement, panelBounds: DOMRect, extraRadius = 0): Circle | null {
    if (rect.height <= 0) return null;
    const circle = {
      x: rect.left + rect.width / 2,
      y: rect.top + rect.height / 2,
      radius: Math.max(11, Math.min(51, Math.hypot(rect.width, rect.height) / 2 + 6)) + extraRadius,
    };
    const {x, y, radius} = circle;
    if (x - radius < 6 || y - radius < 6 || x + radius > innerWidth - 6 || y + radius > innerHeight - 6) return null;
    if (x + radius > panelBounds.left - 8 && x - radius < panelBounds.right + 8 &&
        y + radius > panelBounds.top - 8 && y - radius < panelBounds.bottom + 8) return null;
    const atPoint = document.elementFromPoint(x, y);
    // Ignore text hidden by menus, fixed controls, or still-unplaced marginalia.
    if (!atPoint || !(target.contains(atPoint) || atPoint.contains(target))) return null;
    return circle;
  }

  function targetCircle(target: HTMLElement, panelBounds: DOMRect): Circle | null {
    const bounds = target.getBoundingClientRect();
    if (bounds.bottom <= 0 || bounds.top >= innerHeight || !target.checkVisibility({checkVisibilityCSS: true, checkOpacity: true})) return null;
    if (bounds.left >= panelBounds.left && bounds.right <= panelBounds.right &&
        bounds.top >= panelBounds.top && bounds.bottom <= panelBounds.bottom) return null;
    if (target.matches('.insertion')) {
      // The opening bracket is generated by ::before. Measure its ink, not the
      // inserted words, and use the first fragment even when the text wraps.
      const first = target.getClientRects()[0];
      if (!first) return null;
      const style = getComputedStyle(target, '::before');
      textMeasure.font = `${style.fontStyle} ${style.fontWeight} ${style.fontSize} ${style.fontFamily}`;
      const glyph = textMeasure.measureText('⌞');
      const fontHeight = glyph.fontBoundingBoxAscent + glyph.fontBoundingBoxDescent;
      const baseline = first.top + (first.height - fontHeight) / 2 + glyph.fontBoundingBoxAscent;
      return visibleCircle(new DOMRect(
        first.left - glyph.actualBoundingBoxLeft,
        baseline - glyph.actualBoundingBoxAscent,
        glyph.actualBoundingBoxLeft + glyph.actualBoundingBoxRight,
        glyph.actualBoundingBoxAscent + glyph.actualBoundingBoxDescent,
      ), target, panelBounds, 10);
    }
    // Empty marks and layout markers have meaningful geometry but no text nodes.
    if (target.matches('.tl, .nr, .lb-vspace, .page-anchor, .sidenote-position') || !target.textContent?.trim()) {
      return visibleCircle(bounds, target, panelBounds);
    }
    // Select a visible word, rather than encircling an entire paragraph/hand.
    const walker = document.createTreeWalker(target, NodeFilter.SHOW_TEXT);
    const font = target.matches('.aq, .hand') ? getComputedStyle(target).fontFamily : null;
    let node: Node | null;
    while ((node = walker.nextNode())) {
      const parent = node.parentElement;
      if (!parent || parent.closest('[aria-hidden="true"]')) continue;
      if (font && getComputedStyle(parent).fontFamily !== font) continue;
      for (const match of node.textContent!.matchAll(/\S+/gu)) {
        const range = document.createRange();
        range.setStart(node, match.index!);
        range.setEnd(node, match.index! + match[0].length);
        for (const rect of range.getClientRects()) {
          const circle = visibleCircle(rect, target, panelBounds);
          if (circle) return circle;
        }
      }
    }
    return null;
  }

  function sampleFor(row: HTMLElement, target: HTMLElement): HTMLElement {
    const example = row.querySelector<HTMLElement>('dd')!;
    const tag = row.dataset.legendTag;
    let selector = '';
    if (tag === 'ul') selector = target.matches('.tul') ? '.tul' : target.matches('.dul') ? '.dul' : '.ul';
    if (tag === 'highlight') selector = `.highlight[data-color="${target.dataset.color === 'red' ? 'red' : 'yellow'}"]`;
    if (tag === 'del') selector = target.querySelector('del') ? 'del:has(del)' : 'del:not(:has(del), del del)';
    if (tag === 'er') selector = target.hasAttribute('data-empty') ? '.er[data-empty]' : '.er:not([data-empty])';
    if (tag === 'sidenote') {
      return [...example.querySelectorAll<HTMLElement>('[data-position]')]
        .find(icon => icon.dataset.position === target.dataset.position) || example;
    }
    if (tag === 'hand') {
      const hand = target.matches('.hand') ? target : [...content.querySelectorAll<HTMLElement>('.hand')]
        .find(hand => hand.dataset.ref === target.dataset.handRef);
      return [...example.querySelectorAll<HTMLElement>('span')]
        .find(sample => hand && getComputedStyle(sample).fontFamily === getComputedStyle(hand).fontFamily) || example;
    }
    return (selector && example.querySelector<HTMLElement>(selector)) || example;
  }

  function draw() {
    scheduled = false;
    overlay.replaceChildren();
    rows.forEach(row => row.removeAttribute('data-connected'));
    if (!panel.matches(':popover-open')) return;
    const activeRow = rows.find(row => row.matches(':hover')) || rows.find(row => row.matches(':focus-visible'));
    if (!activeRow) return;
    const panelBounds = panel.getBoundingClientRect();
    const clip = scroller.getBoundingClientRect();
    const paths = document.createDocumentFragment();
    for (const row of rows) {
      if (row !== activeRow) continue;
      const rowBounds = row.getBoundingClientRect();
      if (rowBounds.bottom <= clip.top || rowBounds.top >= clip.bottom) continue;
      const tag = row.dataset.legendTag!;
      const selector = selectors[tag];
      if (!selector) continue;
      const candidates = [...content.querySelectorAll<HTMLElement>(selector)].filter(target =>
        target.closest('.letter-body, .margin-note, .unplaced-note, .page-margin, .hand-label, .hand-key'),
      ).flatMap(target => {
        const circle = targetCircle(target, panelBounds);
        if (!circle) return [];
        const sample = sampleFor(row, target).getBoundingClientRect();
        const y = sample.top + sample.height / 2;
        if (y < clip.top + 5 || y > clip.bottom - 5) return [];
        let kind = tag;
        let pairKey: string | undefined;
        if (tag === 'page') {
          const marker = target.matches('.page-anchor');
          kind = marker ? 'page-marker' : 'page-number';
          pairKey = marker ? target.id : target.closest<HTMLElement>('.page-number')?.dataset.anchor;
        } else if (tag === 'hand') {
          const text = target.matches('.hand');
          kind = text ? 'hand-text' : 'hand-name';
          pairKey = text ? target.dataset.ref : target.dataset.handRef;
        }
        return [{circle, y, kind, pairKey, score: Math.abs(circle.y - y) + Math.abs(circle.x - panelBounds.right) * .2}];
      });
      const selected = selectLegendTargets(candidates, tag === 'page' ? ['page-marker', 'page-number']
        : tag === 'hand' ? ['hand-text', 'hand-name'] : null);
      for (const best of selected) {
        const start = {x: panelBounds.right + 12, y: best.y};
        const {x, y, radius} = best.circle;
        // Leave through the right edge; targets above/below the panel route around it.
        const outsideX = Math.min(innerWidth - 6, Math.max(start.x + 16, Math.min(x - radius - 12, start.x + 80)));
        const endX = x > panelBounds.right ? x - radius : x + radius;
        const path = document.createElementNS(svgNS, 'path');
        path.setAttribute('d', `M ${start.x + 3.5} ${start.y} C ${outsideX} ${start.y}, ${outsideX} ${y}, ${endX} ${y}`);
        const group = document.createElementNS(svgNS, 'g');
        group.dataset.legendTag = tag;
        group.dataset.targetKind = best.kind;
        if (best.pairKey) group.dataset.pairKey = best.pairKey;
        group.append(path);
        for (const [point, r, className] of [[start, 3.5, 'legend-connection-dot'], [best.circle, radius, 'legend-connection-target']] as const) {
          const endpoint = document.createElementNS(svgNS, 'circle');
          endpoint.setAttribute('cx', String(point.x));
          endpoint.setAttribute('cy', String(point.y));
          endpoint.setAttribute('r', String(r));
          endpoint.setAttribute('class', className);
          group.append(endpoint);
        }
        paths.append(group);
        row.dataset.connected = 'true';
      }
    }
    overlay.append(paths);
  }

  function schedule() {
    if (!scheduled && panel.matches(':popover-open')) {
      scheduled = true;
      requestAnimationFrame(draw);
    }
  }
  panel.addEventListener('beforetoggle', event => {
    if (event.newState === 'closed') {
      overlay.replaceChildren();
      rows.forEach(row => row.removeAttribute('data-connected'));
    }
  });
  panel.addEventListener('toggle', () => {
    if (panel.matches(':popover-open')) schedule();
    else { overlay.replaceChildren(); rows.forEach(row => row.removeAttribute('data-connected')); }
  });
  for (const row of rows) {
    row.addEventListener('pointerenter', schedule);
    row.addEventListener('pointerleave', schedule);
    row.addEventListener('focusin', schedule);
    row.addEventListener('focusout', schedule);
  }
  document.addEventListener('scroll', schedule, {capture: true, passive: true});
  window.addEventListener('resize', schedule);
  document.addEventListener('margins:arranged', schedule);
  document.fonts.addEventListener('loadingdone', schedule);
  document.fonts.ready.then(schedule);
  const observer = new ResizeObserver(schedule);
  observer.observe(content);
  observer.observe(panel);
}
