export interface LegendEntry {
  tag: string; xml: string; example: string; meaning: string;
  group: string; label: string; short: string; quickExample?: string;
}

export const legend: LegendEntry[] = [
  {tag:'aq',group:"Hauptsächlich in der Handschrift", label:"Text in lateinischer Schrift", short:"",  xml:'<aq>', example:'<span class="aq" lang="la">Amice carissime</span>', meaning:'Leicht vergrößerte serifenlose Schrift zum optischen Ausgleich; zugleich als Latein ausgezeichnet.'},
  {tag:'b',group:"Hauptsächlich im Druck", label:"Fettdruck", short:"", quickExample:"<strong>Wort</strong>",  xml:'<b>', example:'<strong>Mein lieber Freund</strong>', meaning:'Fettdruck.'},
  {tag:'it',group:"Hauptsächlich im Druck", label:"Kursivdruck", short:"", quickExample:"<em>Wort</em>",  xml:'<it>', example:'<em>Mein lieber Freund</em>', meaning:'Kursivschrift.'},
  {tag:'large',group:"Hauptsächlich in der Handschrift", label:"Größere Schrift", short:"", quickExample:"<span class=\"large\">Wort</span>",  xml:'<large>', example:'<span class="large">Mein lieber Freund</span>', meaning:'Vergrößerte Schrift.'},
  {tag:'ul',group:"Hauptsächlich in der Handschrift", label:"Unterstrichen", short:"", quickExample:'<div class="quick-legend-variants"><span class="ul">Einfach</span><span class="dul">Zweifach</span><span class="tul"><span class="tul-second"><span class="tul-third">Dreifach</span></span></span></div>',  xml:'<ul> / <dul> / <tul>', example:'<span class="ul">Mein lieber Freund</span>', meaning:'Einfache Unterstreichung.'},
  {tag:'sup',group:"Schrift", label:"Hochgestellt", short:"",  xml:'<sup>', example:'Wort<sup>hoch</sup>', meaning:'Hochgestellter Text.'},
  {tag:'sub',group:"Schrift", label:"Tiefgestellt", short:"",  xml:'<sub>', example:'Wort<sub>tief</sub>', meaning:'Tiefgestellter Text.'},
  {tag:'dul',group:"Auszeichnungen", label:"Doppelt unterstrichen", short:"", quickExample:"<span class=\"dul\">Wort</span>",  xml:'<dul>', example:'<span class="dul">Mein lieber Freund</span>', meaning:'Doppelte Unterstreichung.'},
  {tag:'tul',group:"Auszeichnungen", label:"Dreifach unterstrichen", short:"", quickExample:"<span class=\"tul\"><span class=\"tul-second\"><span class=\"tul-third\">Wort</span></span></span>",  xml:'<tul>', example:'<span class="tul"><span class="tul-second"><span class="tul-third">Mein lieber Freund</span></span></span>', meaning:'Dreifache Unterstreichung.'},
  {tag:'del',group:"Hauptsächlich in der Handschrift", label:"Streichungen", short:"", quickExample:'<div class="quick-legend-variants"><del>gestrichen</del><del><del>zweifach</del></del></div>', xml:'<del> / <del><del>…</del></del>', example:'<del>gestrichen</del><br><del><del>zweifach gestrichen</del></del>', meaning:'Durchstreichung; verschachtelte Tilgungen werden doppelt durchgestrichen.'},
  {tag:'er',group:"Hauptsächlich in der Handschrift", label:"Tilgung", short:"Gegebenenfalls mit lesbarem Text.", quickExample:'<span class="er" data-empty="true" role="img" aria-label="Tilgung ohne lesbaren Text"><span aria-hidden="true">getilgter Text</span></span><br><span class="er">getilgter Text</span>',  xml:'<er>', example:'<span class="er">getilgter Text</span>', meaning:'Tilgung. Vorhandener Text und Unleserlichkeitszeichen erscheinen invers. Ohne lesbaren Text bleibt nur der dunkle Balken; Unleserlichkeitszeichen werden ausgeblendet.'},
  {tag:'insertion',group:"Hauptsächlich in der Handschrift", label:"Einfügung", short:"Pfeile zeigen die Position der Einfügung.", quickExample:"<span class=\"insertion\">Zusatz</span><br><span class=\"insertion\" data-pos=\"top\"><span class=\"insertion-arrow\" aria-hidden=\"true\"></span>oben</span>",  xml:'<insertion> / <insertion pos="top|bottom|left|right">', example:'<span class="insertion">Zusatz</span><br><span class="insertion" data-pos="top"><span class="insertion-arrow" aria-hidden="true"></span>oben</span> · <span class="insertion" data-pos="bottom"><span class="insertion-arrow" aria-hidden="true"></span>unten</span><br><span class="insertion" data-pos="left"><span class="insertion-arrow" aria-hidden="true"></span>links</span> · <span class="insertion" data-pos="right"><span class="insertion-arrow" aria-hidden="true"></span>rechts</span>', meaning:'Einfügung zwischen kleinen Winkeln. Bei einer Positionsangabe weist ein kleiner Pfeil von der ursprünglichen Position zum Text.'},
  {tag:'subst',group:"Hauptsächlich in der Handschrift", label:"Überschreibung", short:"", quickExample:"<span class=\"subst\"><del>alt</del><span class=\"insertion\">neu</span></span>",  xml:'<subst>', example:'<span class="subst"><del>altes Wort</del><span class="insertion">neues Wort</span></span>', meaning:'Ersetzung durch Überschreibung. Auf den gestrichenen ursprünglichen Text folgt unmittelbar der eingesetzte Text zwischen Einfügungswinkeln. Ein kleines schwarzes Quadrat nach dem öffnenden Winkel kennzeichnet die Überschreibung.'},
  {tag:'undo',group:"Hauptsächlich in der Handschrift", label:"Rücknahme", short:"", quickExample:"<span class=\"undo\"><del>Wort</del></span>",  xml:'<undo>', example:'<span class="undo"><del>gestrichenes Wort</del></span>', meaning:'Gepunktete Unterstreichung kennzeichnet die Rücknahme einer Auszeichnung. Die ursprüngliche Auszeichnung bleibt sichtbar.'},
  {tag:'ink',group:"Hauptsächlich in der Handschrift", label:"Tinte", short:"", quickExample:"<span class=\"ink\">Wort</span>",  xml:'<ink>', example:'<span class="ink">Mein lieber Freund</span>', meaning:'Dunkelblaue Schrift.'},
  {tag:'pe',group:"Hauptsächlich in der Handschrift", label:"Bleistift", short:"", quickExample:"<span class=\"pe\">Wort</span>",  xml:'<pe>', example:'<span class="pe">Mein lieber Freund</span>', meaning:'Graue Schrift für Bleistift.'},
  {tag:'hand',group:"Hauptsächlich in der Handschrift", label:"Unterschiedliche Schriftschnitte", short:"Hände mit Namen am Rand.", quickExample:'<span data-hand-style="base">Aa</span> <span data-hand-style="second">Aa</span> <span data-hand-style="third">Aa</span>',  xml:'<hand ref="…">', example:'<div class="legend-margin-example"><aside>Hand<br>Friedrich David Lenz</aside><span class="hand">Mein lieber Bruder</span></div>', meaning:'Unterscheidung der Hände durch verschiedene Schriftschnitte und Angabe der schreibenden Person am rechten Rand.'},
  {tag:'highlight',group:"Hauptsächlich in der Handschrift", label:"Farbige Hervorhebung", short:"", quickExample:"<mark class=\"highlight\" data-color=\"yellow\">Wort</mark> <mark class=\"highlight\" data-color=\"red\">Wort</mark>",  xml:'<highlight color="yellow|red">', example:'<mark class="highlight" data-color="yellow">gelb hervorgehobener Text</mark><br><mark class="highlight" data-color="red">rot hervorgehobener Text</mark>', meaning:'Farbige Hervorhebung. Erlaubte Werte für „color“: „yellow“ (gelb) und „red“ (rot).'},
  {tag:'note',group:"Editorische Hinweise", label:"Anmerkungen der Editoren", short:"", quickExample:"<span class=\"note\">Anmerkung</span>",  xml:'<note>', example:'Text <span class="note">Anmerkung</span><div class="lb-line-block lb-line-block--note"><span class="note">alleinstehende Anmerkung</span></div>', meaning:'Grau und in eckigen Klammern. Steht die Anmerkung allein in einer Zeile, wird sie zentriert.'},
  {tag:'tl',group:"Editorische Hinweise", label:"Textverlust", short:"Der jeweilige Grund für den Textverlust ist in den Anmerkungen erläutert.",  xml:'<tl>', example:'vor <span class="tl"></span> nach', meaning:'Textverlust, gekennzeichnet durch einen gepunkteten Kreis.'},
  {tag:'nr',group:"Editorische Hinweise", label:"Unentziffert", short:"Der Abstand der Marker entspricht dem ungefähren Umfang der unentzifferten Stelle.",  xml:'<nr/> / <nr extent="4"/>', example:'<span class="nr" data-extent="1" style="--extent:1"></span> / <span class="nr" data-extent="4" style="--extent:4"></span>', meaning:'Unleserliche Stelle zwischen hohlen Punkten. Der Abstand folgt dem Umfang in Zeichen; ohne Angabe eine Zeichenbreite.'},
  {tag:'anchor',group:"Hinweise und Verweise", label:"Verweiszeichen", short:"Verbindet Text und Anmerkung.", quickExample:"<span>Wort<span class=\"anchor\"><sup>1</sup></span></span>",  xml:'<anchor>', example:'Wort<span class="anchor">1</span> · Wort<span class="anchor"><sup>1</sup></span>', meaning:'Strukturelle Kennzeichnung eines Verweiszeichens, ohne eigene Formatierung. Hochstellung wird mit <sup> innerhalb von <anchor> ausgezeichnet.'},
  {tag:'fn',group:"Hinweise und Verweise", label:"Fußnote", short:"Berühren oder fokussieren zeigt vorhandene Verbindungslinien.", quickExample:"<span class=\"fn\"><span class=\"anchor\"><sup>1</sup></span> Anmerkung</span>",  xml:'<fn index="1">', example:'<span class="fn" data-index="1"><span class="anchor"><sup>1</sup></span> Eine Fußnote.</span>', meaning:'Fußnotentext im Textfluss. Die Nummer wird als Zuordnung beibehalten; keine zusätzliche Gestaltung des Textes.'},
  {tag:'address',group:"Anordnung", label:"Adresse", short:"Ohne besondere Formatierung.", quickExample:"An meinen lieben Freund",  xml:'<address>', example:'An meinen lieben Freund', meaning:'Keine eigene Gestaltung; der Inhalt bleibt erhalten.'},
  {tag:'gr',group:"Sprachen", label:"Altgriechisch", short:"",  xml:'<gr>', example:'<span lang="grc">λόγος</span>', meaning:'Altgriechisch (lang="grc"); keine zusätzliche Formatierung.'},
  {tag:'fr',group:"Sprachen", label:"Französisch", short:"",  xml:'<fr>', example:'<span lang="fr">Mon cher ami</span>', meaning:'Französisch (lang="fr"); keine zusätzliche Formatierung.'},
  {tag:'hb',group:"Sprachen", label:"Hebräisch", short:"",  xml:'<hb>', example:'<span lang="he">שלום</span>', meaning:'Hebräisch (lang="he"); keine zusätzliche Formatierung.'},
  {tag:'ru',group:"Sprachen", label:"Russisch", short:"",  xml:'<ru>', example:'<span lang="ru">Дорогой друг</span>', meaning:'Russisch (lang="ru"); keine zusätzliche Formatierung.'},
  {tag:'line',group:"Anordnung", label:"Zeile und Einzug", short:"Einzüge gelten nur für die erste Zeile.", quickExample:"<div class=\"lb-line-block\">Neue Zeile</div><div class=\"lb-line-block\" data-tab=\"1\" style=\"--indent-units:1\">Eingerückt</div><hr class=\"lb-rule\">",  xml:'<line/> / <line tab="2"/> / <line type="line"/>', example:'<div class="lb-line-block">Neue Zeile</div><div class="lb-line-block" data-tab="2" style="--indent-units:2">Nur die erste Zeile ist eingerückt. Automatisch umgebrochene Folgezeilen beginnen wieder am linken Rand.</div><div class="lb-line-block lb-line-block--rule"><hr class="lb-rule"></div>', meaning:'Semantischer Zeilenbeginn. „tab“ rückt nur die erste dargestellte Zeile ein, nicht den gesamten Absatz; „type=line“ ergänzt eine horizontale Linie.'},
  {tag:'line-tilde',group:"Anordnung", label:"Geschwungener Strich", short:"",  xml:'<line type="tilde"/>', example:'<div class="lb-line-block lb-line-block--rule"><span class="lb-ornament lb-ornament--tilde" role="img" aria-label="Geschwungener Strich"></span></div>', meaning:'Zentrierter geschwungener Strich als Schmuckzeichen auf einer eigenen Zeile.'},
  {tag:'line-double-tilde',group:"Anordnung", label:"Doppelter geschwungener Strich", short:"",  xml:'<line type="double-tilde"/>', example:'<div class="lb-line-block lb-line-block--rule"><span class="lb-ornament lb-ornament--double-tilde" role="img" aria-label="Doppelter geschwungener Strich"></span></div>', meaning:'Zwei nebeneinanderstehende geschwungene Striche als zentriertes Schmuckzeichen auf einer eigenen Zeile.'},
  {tag:'vspace',group:"Layout", label:"Leerräume", short:"Außer zwischen Seitenumbrüchen bildet der Leerraum die edierte Quelle mimetisch ab.", quickExample:"<div>Text</div><div class=\"lb-vspace\" style=\"height:.6lh\"></div><div>Text</div>",  xml:'<vspace lines="1"/>', example:'<div class="lb-line-block">Vor dem Abstand</div><div class="lb-vspace" data-lines="1" style="height:1lh"></div><div class="lb-line-block">Nach dem Abstand</div>', meaning:'Vertikaler Abstand in Zeilenhöhen. Beendet den bisherigen Zeilenkontext; danach beginnt eine neue Zeile.'},
  {tag:'align',group:"Anordnung", label:"Ausrichtung", short:"Links, mittig oder rechts.", quickExample:"<div class=\"align-left\">links</div><div class=\"align-center\">mittig</div><div class=\"align-right\">rechts</div>",  xml:'<align pos="left|center|right">', example:'<div class="lb-line-block" data-layout="aligned"><div class="align-left">links</div><div class="align-center">mittig</div><div class="align-right">rechts</div></div>', meaning:'Linke, mittige oder rechte Ausrichtung innerhalb einer Zeile; mehrere Bereiche sind kombinierbar.'},
  {tag:'tabs',group:"Anordnung", label:"Spalten", short:"Mehrere Zeilen in Spalten.",  xml:'<tabs>', example:'<div class="tabs"><div class="lb-tab-row"><div class="tab" style="--cell-width:50%">erste Spalte</div><div class="tab" style="--cell-width:50%">zweite Spalte</div></div><div class="lb-tab-row"><div class="tab" style="--cell-width:50%">darunter</div><div class="tab" style="--cell-width:50%">darunter</div></div></div>', meaning:'Zusammengehörige Zeilen mit frei positionierten Spalten.'},
  {tag:'tab',group:"Anordnung", label:"Spaltenbereich", short:"Text beginnt an einer festen Position.",  xml:'<tab value="1-2"> / <tab value="2-2">', example:'<div class="lb-tab-row"><div class="tab" data-value="1-2" style="--cell-width:50%">links</div><div class="tab" data-value="2-2" style="--cell-width:50%">ab der Hälfte</div></div>', meaning:'Ein einzelner Spaltenbereich. Die Positionsangabe unterteilt die Zeile; hier beginnt die zweite Spalte bei der Hälfte.'},
  {tag:'page',group:"Layout", label:"Seitenwechsel", short:"Seitenzahlen links; ein vertikaler Strich markiert den Wechsel im laufenden Text.", quickExample:"<span style=\"font-family:var(--font-sans)\">2</span> &nbsp; Text<span class=\"page-anchor\" data-break=\"inline\"></span>Text",  xml:'<page index="2"/>', example:'<div class="page-number">2</div><div>Der Text geht<span class="page-anchor" data-break="inline"></span>auf der neuen Seite weiter.</div>', meaning:'Kleine serifenlose Seitenzahl rechtsbündig in der linken Randspalte. Innerhalb eines Textblocks markiert „ | “ den Seitenwechsel; an einem Blockbeginn entfällt die Markierung. Eine erste Seite mit der Nummer 1 wird nicht beschriftet.'},
  {tag:'sidenote',group:"Layout", label:"Randnotizen", short:"Möglichst zu Anfang der Seite. Die Symbole zeigen die Position auf der Briefseite.", quickExample:"<div class=\"quick-legend-margin-sample\"><span>Brieftext</span><aside>Randnotiz</aside></div>",  xml:'<sidenote page="2" pos="left">', example:'<div class="legend-margin-example"><aside>Randnotiz<br>zur Seite 2</aside><div>Brieftext auf der zugehörigen Seite.</div></div>', meaning:'Randnotiz am Beginn der zugehörigen Seite im rechten Rand. Auf schmalen Bildschirmen steht sie unter dem Brieftext; unzugeordnete Notizen bleiben ebenfalls erhalten.'},
];

// Most frequent first within each section, counted in briefe.xml (including
// sidenotes). Underlining combines ul/dul/tul; spacing excludes presentational gaps.
const quickLegendTags = [
  'it', 'b',
  'ul', 'aq', 'del', 'insertion', 'hand', 'pe', 'subst', 'er', 'ink', 'highlight', 'large', 'undo',
  'note', 'tl', 'nr',
  'page', 'vspace', 'sidenote',
];
export const quickLegend = quickLegendTags.flatMap(tag => legend.filter(item => item.tag === tag));

export const legendGroups = ['Hauptsächlich im Druck', 'Hauptsächlich in der Handschrift', 'Editorische Hinweise', 'Layout'];
