name: XML prüfen

on:
  push:
    paths:
      - 'data/xml/**/*.xml'
  pull_request:
    paths:
      - 'data/xml/**/*.xml'

jobs:
  Verweise:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Python-Setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Abhängigkeiten installieren
      run: |
        python -m pip install --upgrade pip
        pip install lxml
      
    - name: Verweise prüfen 
      run: python Scripts/lint_verweise.py
